Add assignments
aravindvnair99/ACM-Amrita-2019-2020-Assignments pull request #48
Opened 2019-11-02 13:08 UTC by adithyaRocks

Fixes #4 

- All 3 assignments

2019-11-02 13:10 UTC, aravindvnair99 requested changes

2019-11-02 13:10 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="date" name="Birthday"><br>
Missing `autocomplete`.

2019-11-02 13:10 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="checkbox" name="Check" value="check"><br>
Missing `required`.

2019-11-02 13:27 UTC, aravindvnair99 requested changes

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/Pokemon .html
> +</html>
Set indentation to tab 4 and format the file.

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="text"  name="First Name" placeholder="First Name" required>
Missing `autocomplete`.

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="text"  name="Last Name" placeholder="Last Name" required>
Missing `autocomplete`.

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Other">
Missing `autocomplete`.

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        Gender:<label for="gender">Male:</label>
`label` not required here.

2019-11-02 13:27 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="email" name="Email" placeholder="Email" required  >
Missing `autocomplete`.

2019-11-04 10:02 UTC, aravindvnair99 commented
@adithyaRocks Shall I close this as you have created another pull request from a separate branch?

2019-11-05 06:31 UTC, VinayakTekade commented
@aravindvnair99 I have taken the other pull request into consideration, please close this pull request.

2019-11-05 14:27 UTC, aravindvnair99 reviewed
@adithyaRocks Merging and closing the pull request for now. Make the necessary changes in another pull request and send it over from a different branch. Also, make sure to fill up the pull request template and also refactor the code henceforth.

2019-11-05 14:27 UTC, merged