sending from a new branch named new
aravindvnair99/ACM-Amrita-2019-2020-Assignments pull request #50
Opened 2019-11-04 05:57 UTC by adithyaRocks

Fixes #4 

## Proposed Changes- changed all

2019-11-04 10:00 UTC, aravindvnair99 requested changes

2019-11-04 10:00 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Other" autocomplete="sex">
- Missing `label`.
- Radio inputs are not compatible with autocomplete.

2019-11-04 10:00 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="text"  name="Last Name" placeholder="Last Name" required autocomplete="name">
Wrong `autocomplete`. Refer this: [The HTML autocomplete attribute
](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

2019-11-04 10:00 UTC, aravindvnair99 commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="date" name="Birthday"><br>
Missing `autocomplete`.

2019-11-04 12:35 UTC, adithyaRocks commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Other" autocomplete="sex">
label wasnt required here right

2019-11-05 06:27 UTC, VinayakTekade submitted a review, later dismissed

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/Pokemon .html
> +    <th><a href="http://pokemon.wikia.com/wiki/Ivysaur">Ivyasaur</a></th>
Use `th` is used only in the first row. Use `td` for other rows.
`th` stands for table heading and `td` stands for table definition.

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/Pokemon .html
> +    <th><a href="http://pokemon.wikia.com/wiki/Charmeleon">Charmeleon</a></th>
Use `td`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/Pokemon .html
> +    <th><a href="http://pokemon.wikia.com/wiki/Wartortle">Wartortle</a></th>
Use `td`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="text"  name="First Name" placeholder="First Name" required autocomplete="given-name">
`for` points to an `id`. See the solution in my folder and use the same values in `for` and `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="text"  name="Last Name" placeholder="Last Name" required autocomplete="family-name">
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Male" >
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Female" >
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="radio" name="gender" value="Other">
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="email" name="Email" placeholder="Email" required autocomplete="email" >
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="password" name="Password" minlength="5" maxlength="15" required autocomplete="new-password">
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="date" name="Birthday" autocomplete="bday"><br>
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented on Adithya/HTMLbasicsremake/form.html
> +        <input type="checkbox" name="Check" value="check" required><br>
Use `id`

2019-11-05 06:27 UTC, VinayakTekade commented
Make the changes and send another pull request.

2019-11-05 14:29 UTC, aravindvnair99 reviewed
@adithyaRocks Merging and closing the pull request for now. Make the necessary changes in another pull request and send it over from a different branch. Also, make sure to fill up the pull request template and also refactor the code henceforth.

2019-11-05 14:29 UTC, merged