added all assignments
aravindvnair99/ACM-Amrita-2019-2020-Assignments pull request #51
Opened 2019-11-05 03:37 UTC by vishnuvkaimal

Fixes #

## Proposed Changes

-
-
-

2019-11-05 06:16 UTC, VinayakTekade submitted a review, later dismissed

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment1.html
> +<p><i>Wikipedia, the free encyclopedia</i></p>
Use `cite` instead of `i`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment1.html
> +<h2><b>Merlo J. Pusey</b></h2>
Use `strong` instead of `b`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment1.html
> +</p>
`p` is not needed. Use `div` instead.

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment1.html
> +<P><b><Contents/b> </P>
Use `strong` instead of  `b`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment3.html
> +    First Name <input type="text" name="FirstName" required>
```suggestion
    First Name <input type="text" name="FirstName" required autocomplete="given-name">
```

This an example of how to use `autocomplete` , use this same format for the other fields marked as `autocomplete` missing

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment3.html
> +    Last Name <input type="text" name="LastName" required>
Missing `autocomplete`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment3.html
> +Email: <input type="email" name="Email" id="email" required>
Missing `autocomplete`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment3.html
> +Password: <input type="password" name="pwd" min="5" max="15" required>
Missing `autocomplete`

2019-11-05 06:16 UTC, VinayakTekade commented on Vishnu/Assignment3.html
> +Birthsday <input type="date" name="birthday">
Missing `autocomplete`

2019-11-06 07:37 UTC, VinayakTekade approved these changes
All the changes made are correct. Nice job.

2019-11-06 08:11 UTC, aravindvnair99 requested changes

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><img src="http://img4.wikia.nocookie.net/__cb20140328190757/pokemon/images/thumb/2/21/001Bulbasaur.png/200px-001Bulbasaur.png" alt=""></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><img src="http://img4.wikia.nocookie.net/__cb20140724195345/pokemon/images/thumb/7/73/004Charmander.png/200px-004Charmander.png" alt=""></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><img src="http://img1.wikia.nocookie.net/__cb20140328191525/pokemon/images/thumb/3/39/007Squirtle.png/200px-007Squirtle.png" alt=""></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><a href="http://pokemon.wikia.com/wiki/Wartortle">Wartortle</a></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><a href="http://pokemon.wikia.com/wiki/Charmeleon">Charmeleon</a></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment2.html
> +        <td><a href="http://pokemon.wikia.com/wiki/Ivysaur">Ivysaur</a></td>
Switch to `HTTPS` for next pull request.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment3.html
> +    Others: <input type="radio" name="Gender" value="others"/>
Add `label`.

2019-11-06 08:11 UTC, aravindvnair99 commented on Vishnu/Assignment3.html
> +Password: <input type="password" name="pwd" min="5" max="15" required autocomplete="current-password">
Wrong `autocomplete` attribute. Should be for a registration form, not login. So should be new and not current as there is no current.

2019-11-07 09:49 UTC, aravindvnair99 commented
@vishnuvkaimal Update your PR description. Use proper GFM syntax henceforth with proper escape characters. Refer this: [GFM - GitHub Guides](https://guides.github.com/features/mastering-markdown/)

2019-11-13 07:53 UTC, aravindvnair99 requested changes
@vishnuvkaimal Make the changes intimated to you on the group.

2019-11-15 15:32 UTC, aravindvnair99 commented
@vishnuvkaimal Closing this pull request due to inactivity. You can send in the right one as a new pull request. Have a look at the video I sent on the group.

2019-11-15 15:32 UTC, closed without merging