Made necessary changes
aravindvnair99/ACM-Amrita-2019-2020-Assignments pull request #54
Opened 2019-11-06 13:17 UTC by PriyaaIyer

Fixes #
- Page Title added (all assignments)
- Changed <b> to <strong> 
- Added <em>
- Added metadata
- Used ordered lists
- Used <thead> and <tbody> tags 
## Proposed Changes

-
-
-

2019-11-07 05:20 UTC, VinayakTekade requested changes

2019-11-07 05:20 UTC, VinayakTekade commented on Priyaa/HTML Basics Remake/Assignment-1.html
> +      D.C.)[1][2] was an <u>American biographer</u> and <u>editorial writer</u>. He won the 1952 Pulitzer Prize for
```suggestion
      D.C.)<sup>[1][2]</sup> was an <u>American biographer</u> and <u>editorial writer</u>. He won the 1952 Pulitzer Prize for
```

2019-11-07 05:20 UTC, VinayakTekade commented on Priyaa/HTML Basics Remake/Assignment-3.html
> +        <h1><b>Register</b></h1>
No need of `b` here, `h1` should be good enough.

2019-11-07 05:20 UTC, VinayakTekade commented on Priyaa/HTML Basics Remake/Assignment-3.html
> +                <input type="text" name="lastname" placeholder="Last Name" autocomplete="family-name" required>
last name 'id' is missing

2019-11-07 05:20 UTC, VinayakTekade commented on Priyaa/HTML Basics Remake/Assignment-3.html
> +                <input type="date" name="birthday" autocomplete="bday" required>
Birthday `id` is missing

2019-11-07 05:20 UTC, VinayakTekade commented on Priyaa/HTML Basics Remake/Assignment-3.html
> +                <label for="terms and conditions"><strong>I agree to the terms and conditions</strong></label><input
terms and conditions `id` is missing

2019-11-07 05:22 UTC, VinayakTekade commented
Nice work. Just these few changes and you are good to go.

2019-11-07 05:56 UTC, PriyaaIyer commented
Made necessary changes, formatted code and pushed it.
Unable to create a new pull request.

On Thu, Nov 7, 2019 at 10:52 AM Vinayak Tekade <notifications@github.com>
wrote:

> Nice work. Just these few changes and you are good to go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aravindvnair99/ACM-Amrita-2019-2020-Assignments/pull/54?email_source=notifications&email_token=ALDAB5OE7T6NKB3JRFCRF3TQSOQX7A5CNFSM4JJUYHJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDKGKWI#issuecomment-550790489>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALDAB5MTJXXQK6KTA6EZRP3QSOQX7ANCNFSM4JJUYHJA>
> .
>

2019-11-07 09:28 UTC, VinayakTekade submitted a review, later dismissed

2019-11-07 09:42 UTC, aravindvnair99 requested changes
- Remove unnecessary spaces.
- Set to tab indentation of 4. You can confirm by looking in VS Code:
![image](https://user-images.githubusercontent.com/22199259/68377673-d9302f00-0170-11ea-8934-4ac1fd29a1ba.png)
- Then format document.

2019-11-07 09:46 UTC, aravindvnair99 commented
@PriyaaIyer I've updated your PR description. Use proper GFM syntax henceforth with proper escape characters. Refer this: [GFM - GitHub Guides](https://guides.github.com/features/mastering-markdown/)

2019-11-07 11:52 UTC, PriyaaIyer commented
Removed unnecessary spaces
Set indentation using tab to 4
Formatted document

On Thu, Nov 7, 2019 at 3:12 PM Aravind V. Nair <notifications@github.com>
wrote:

> *@aravindvnair99* requested changes on this pull request.
>
>    - Remove unnecessary spaces.
>    - Set to tab indentation of 4. You can confirm by looking in VS Code:
>    [image: image]
>    <https://user-images.githubusercontent.com/22199259/68377673-d9302f00-0170-11ea-8934-4ac1fd29a1ba.png>
>    - Then format document.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aravindvnair99/ACM-Amrita-2019-2020-Assignments/pull/54?email_source=notifications&email_token=ALDAB5IW5DRSP2YUVOLTA6LQSPPH3A5CNFSM4JJUYHJKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCKVUGEY#pullrequestreview-313213715>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALDAB5N2SM2IGDXO5YTTNX3QSPPH3ANCNFSM4JJUYHJA>
> .
>

2019-11-13 07:52 UTC, aravindvnair99 requested changes
@PriyaaIyer Make the changes intimated to you on the group.

2019-11-15 14:13 UTC, closed without merging